sonar.projectKey=jpmorganchase_fusion
sonar.organization=jpmorganchase
sonar.python.version=3.9,3.10,3.11,3.12,3.13
sonar.sources=py_src
sonar.tests=py_tests,py_integ
sonar.python.coverage.reportPaths=.reports/py/coverage.xml
